### PR TITLE
Add Benchmark licenses

### LINKED ISSUE #322: Add benchmark licenses
Add benchmark licenses to all benchmarks.

### PR DESCRIPTION
**Pull request by Danidite**
Closes #322

### CODE REVIEW

**Comment by engshahrad** [comment]
I have not been marked as a reviewer yet. Is there anything left to be done for this PR before I can review @Danidite ? Thanks

**Comment by Danidite** [comment]
> I have not been marked as a reviewer yet. Is there anything left to be done for this PR before I can review @Danidite ? Thanks

The only thing missing are licenses for MapReduce and FEM; while I don't think we used any external pieces of code for FEM, I am unsure about MapReduce. @jerryyiransun, can you confirm if either of those benchmarks uses any external code? If so, can you add licenses for them?

**Comment by jerryyiransun** [comment]
> > I have not been marked as a reviewer yet. Is there anything left to be done for this PR before I can review @Danidite ? Thanks
> 
> The only thing missing are licenses for MapReduce and FEM; while I don't think we used any external pieces of code for FEM, I am unsure about MapReduce. @jerryyiransun, can you confirm if either of those benchmarks uses any external code? If so, can you add licenses for them?

The MapReduce and FEM benchmarks did not use any external code, so no need to add licenses for them

**Review by engshahrad — APPROVED** [review]
lgtm. thanks

**Pull request merged**
